aboutpage
IEEE-AlAzhar/Official-Website pull request #1
Opened 2020-04-10 21:46 UTC by moatazalaa14

2020-04-12 01:08 UTC, dvmhmdsd requested changes
1. Don't change the name of `css` files, leave it as `style.module.css` as it's and use `css modules` as noted in `README` file.

2. Use the `container` class from bootstrap to add side spaces.

3. Add the logo of the team not the `IEEE Club`.

4. Add support to dark mode.

5. Make the image life under paragraph in medium screen.

6. Add heading to the page --> h1

2020-04-12 01:08 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/components/IEEEAZAHARSec/IEEEAZAHARSec.css
> +    .IEEEAZALogo img{
Use `BEM` methodology to name classes.

2020-04-12 01:08 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/components/IEEEAZAHARSec/IEEEAZAHARSec.css
> +    width: 45vw;
Don't add fixed width

2020-04-12 01:08 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/components/IEEEAZAHARSec/IEEEAZAHARSec.css
> +    width: 40vw;
Don't add fixed width

2020-04-12 01:08 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/components/IEEEAZAHARSec/IEEEAZAHARSec.js
> +  const AZAlogo = useRef();
Don't use hooks.

2020-04-12 01:08 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/components/IEEEAZAHARSec/IEEEAZAHARSec.js
> +  useEffect(() => {
Don't use hooks

2020-04-12 01:08 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/components/IEEEAZAHARSec/IEEEAZAHARSec.js
> +        <h2>IEEE-AZAHAR</h2>
Why did u use `h2` here? is this the right place ? (semantic)

2020-04-12 01:08 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/components/headerForAboutPage/HeaderForAboutPage.css
> +#header-about{
Use classes not ids in styling

2020-04-12 01:08 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/components/publicIEEESec/PublicIEEESec.js
> +import IEEEPubLogo from "./../../../../../../../assets/IEEE-pub-logo.jpg";
Why did u rename the image?

2020-04-12 01:08 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/index.js
> +      <Layout />
Use `Layout` like this :
```
<Layout>
 <HeaderForAboutPage />
      <PublicIEEESec />
      <IEEEAZAHARSec />
      <IEEEStructure />
</Layout>
```

and remove the footer, it's added already inside the `Layout` component.

2020-04-12 01:08 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/style.module.css
> +.aboutpage-dark{
You don't need to set the bg of the page in the dark mode, it has already set in the body.

2020-04-12 02:43 UTC, moatazalaa14 commented on src/modules/static-pages/about/components/page/components/IEEEAZAHARSec/IEEEAZAHARSec.css
> +    width: 40vw;
???i make it taking auto width ??

2020-04-12 02:50 UTC, moatazalaa14 commented on src/modules/static-pages/about/components/page/components/IEEEAZAHARSec/IEEEAZAHARSec.js
> +        <h2>IEEE-AZAHAR</h2>
> <h1> headings should be used for main headings, followed by <h2> headings, then the less important <h3>, and so on.
الي فهمته ان يكون في h1 بعد كدا ابدا ادرج فيهم 
فانا فاهم غلط ؟

2020-04-12 02:52 UTC, moatazalaa14 commented on src/modules/static-pages/about/components/page/components/publicIEEESec/PublicIEEESec.js
> +import IEEEPubLogo from "./../../../../../../../assets/IEEE-pub-logo.jpg";
عشان الصور الي موجود فالصفحة كلها صور هيتحط عليها شروط فبدل ما اتعامل مع الpath الكبير دة
اتعامل مع الاسم

2020-04-12 12:22 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/components/IEEEAZAHARSec/IEEEAZAHARSec.css
> +    width: 40vw;
Yup

2020-04-12 12:23 UTC, dvmhmdsd commented on src/modules/static-pages/about/components/page/components/IEEEAZAHARSec/IEEEAZAHARSec.js
> +        <h2>IEEE-AZAHAR</h2>
انت كده فاهم كويس جدا بس ال 
h1
فين ؟

2020-04-13 00:34 UTC, dvmhmdsd reviewed
1. Don't change the name of the files , leave it `index.js` & `style.module.css`.

2. The names of components is not appropriate, and has typos e.g: `IEEEAZAHARSec` ==> `IEEEAZHARSection`

3. Class names are not descriptive.

4. Don't add fixed width to images.

5. Use the `IntersectionObserver` for the video only.

2020-04-13 00:36 UTC, merged