Single Event Page!
IEEE-AlAzhar/Official-Website pull request #13
Opened 2020-04-23 08:30 UTC by Esmail99

I've added 3 packages.. 
1) react-responsive-modal: to add a nice popup modal. 
2) react-dynamic-form-builder: to help with dynamic form implementation.
3) core-js: to fix previous package issues.

2020-04-23 11:27 UTC, dvmhmdsd requested changes
- ` StartTime` is optional, check `/events/5`

- The pullets of the gallery carousel is not accessible.

2020-04-23 11:27 UTC, dvmhmdsd commented on src/modules/events/components/singleEventPage/components/EventDetails/EventDetails.js
> +class Gallery extends Component {
Is this component `Gallery` or `EventDetails`

2020-04-23 11:27 UTC, dvmhmdsd commented on src/modules/events/components/singleEventPage/components/ApplyButton/style.module.css
> +@keyframes :local(customEnterAnimation) {
I get an error here from `eslint` 

`Identifier expected`

2020-04-23 11:27 UTC, dvmhmdsd commented on src/modules/events/components/singleEventPage/components/Gallery/Gallery.js
> +        <h3 className='h3 mt-5 mb-4' style={{ color: "var(--text-secondary)" }}>Event Gallery</h3>
This should be `h2`

2020-04-23 11:27 UTC, dvmhmdsd commented on src/shared/Input.js
> +      e.target.classList.add(this.props.classes);
It should be `className` to get the default `className` of the element. And if didn't use it, remove the file.

2020-04-23 11:30 UTC, dvmhmdsd commented
It should show `Not Found` of the id in the `url` is not in the events data.

2020-04-23 17:17 UTC, Esmail99 commented
> It should show `Not Found` if the id in the `url` is not in the events data.

I think we should build a nice 404 NOT FOUND component.

2020-04-23 18:10 UTC, dvmhmdsd commented
> > It should show `Not Found` if the id in the `url` is not in the events data.
> 
> I think we should build a nice 404 NOT FOUND component.

We'll, as in the `TODOs` file. But make it for now like the `singleServicePage`.

2020-04-24 11:14 UTC, dvmhmdsd requested changes
1. Make the components independant. (Apply button shouldn't have the `cover & `form`).

2020-04-24 13:41 UTC, merged