Eventslist(upcomingevents)
IEEE-AlAzhar/Official-Website pull request #8
Opened 2020-04-20 20:19 UTC by moatazalaa14

2020-04-20 22:56 UTC, dvmhmdsd requested changes
1. Don't rename the components, leave it `eventsListPage` as it's and don't modify the structure of the folders please.

2. Use the `EventCard` component and pass props to it.

3. Make the events data `async` by getting it from the  `events.json` in the public folder (see bestMembers component for illustration).

2020-04-20 22:56 UTC, dvmhmdsd commented on src/modules/events/components/eventsListPage/components/upComingEvents/index.js
> +        <h1 className={styles.eventsList__heading}>UpComing Events</h1>
The heading is `Our Events`

2020-04-20 22:56 UTC, dvmhmdsd commented on src/modules/events/components/eventsListPage/components/upComingEvents/style.module.css
> +    width: 80vw;
Why did u add a fixed width and height ???

2020-04-20 22:56 UTC, dvmhmdsd commented on src/modules/events/components/eventsListPage/components/upComingEvents/style.module.css
> +.eventsList{
Use `BEM` --> `events-list`

2020-04-20 22:56 UTC, dvmhmdsd commented on src/modules/events/components/eventsListPage/components/upComingEvents/style.module.css
> +.upcomingEvent{
Use `BEM` --> `upcoming-event`, and please use a descriptive class names.

2020-04-20 23:11 UTC, dvmhmdsd requested changes
- There should be 3 cards in the row on desktop, 2 on tablet and 1 on mobile.

- Don't add any style for the card and use the `EventCard` component.

- Don't add any bg-image please.

2020-04-22 16:53 UTC, dvmhmdsd requested changes
1. Use the `eventCard` component and pass the data of the event to it.
2. You didn't do anything for making the page responsive.

2020-04-22 18:48 UTC, dvmhmdsd commented
- Add the title of the page `Our events`, and a heading for upcoming event and another heading for past events. Also please use the  `eventCard` Component.

2020-04-23 10:56 UTC, dvmhmdsd commented
You should do the following:

1. Request the events.
2. Update the state with the response.
3. In JSX:
   - Loop across the data in the state.
   - Pass the single object to `eventCard` Component

--> Consider this code for illustration:
```js
events.map(singleEvent => {
   return (
      <div className="custom-class">
         <EventCard event={singleEvent} />
     </div>
   )
});
```

2020-04-25 00:09 UTC, IEEE-AlAzhar requested changes

2020-04-25 00:09 UTC, IEEE-AlAzhar commented on src/modules/events/components/eventsListPage/index.js
> +            <h1 className={styles[`past-heading`]}>Past events</h1>
There should be just 1 `h1` on the page.

2020-04-25 00:09 UTC, IEEE-AlAzhar commented on src/modules/events/components/eventsListPage/index.js
> +                      <div>
This div is not appropriate.

2020-04-25 00:17 UTC, IEEE-AlAzhar requested changes
- The UI is not appropriate as the cards don't have side spaces.

- The `upcoming` event shouldn't fill the whole space of the row.

- The titles should be:
`h1` Our events
`h2` upcoming events
`h2` past events

2020-04-25 00:17 UTC, IEEE-AlAzhar commented on src/modules/events/components/eventsListPage/index.js
> +        {this.state.eventsList ? console.log(this.state.eventsList) : null}
Console !!!

2020-04-25 00:17 UTC, IEEE-AlAzhar commented on src/modules/events/components/eventsListPage/index.js
> +          <div className={styles[`events-container`]}>
Please use `bootstrap grid` to make the responsive more easier.

2020-04-27 01:45 UTC, dvmhmdsd commented
1. Use `bootstrap`'s grid please.
2. If there's multiple upcoming events, they should be beside each other, if there's only 1 upcoming event, it should be alone in the row but don't take the whole row.

2020-04-28 19:13 UTC, dvmhmdsd requested changes

2020-04-28 19:13 UTC, dvmhmdsd commented on src/modules/events/components/eventsListPage/index.js
> +                        <div className="lg-col-12 md-col-12 sm-col-12 mt-4">
The `key` prop should be here not in eventCard

2020-04-28 19:13 UTC, dvmhmdsd commented on src/modules/events/components/eventsListPage/index.js
> +                          <div className="col-lg-4 col-md-6 col-sm-12 mt-4">
Same here...

2020-04-28 19:16 UTC, dvmhmdsd commented
The `upcoming` events should be beside each other and the card should take it's normal width and doesn't fill the whole row if it's single.

2020-04-28 19:18 UTC, dvmhmdsd commented
Also there should be a padding for the list to get more space above the footer. Also use semantics and divide the page into sections. 
```html
<h1> .. </h1>
<section>
   <h2> .. </h2>
   ....
</section>
<section>
   <h2> .. </h2>
   ....
</section>
```

2020-04-28 23:52 UTC, dvmhmdsd commented
Your work is awesome buddy, last edit: Center the upcoming events cards, so that if there's only one upcoming event it should be at the center.

2020-04-29 00:19 UTC, merged